name: test_deploy

on: 
  push:
    branches: 
      - main

jobs:

  deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS dev with SSH ACTION
        uses: appleboy/ssh-action@master
        env:
          GTOKEN: ${{ secrets.SSH_TOKEN_WEB_AZAMAT }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: GTOKEN
          script:  |
            echo "Hello world!"
